-- Idempotent seed: page rows + their SEO from shared/pageMeta.json.
-- Safe to run any number of times. Uses dollar-quoted strings to avoid apostrophe issues.
BEGIN;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/$tag$, $tag$AI Visibility Tracker & Audit | LLMClicks.ai$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$AI Visibility Tracker & Audit | LLMClicks.ai$tag$, $tag$Measure your brand's AI search visibility across LLMs. Track citations, analyze competitors, and optimize for generative engines with LLMClicks.ai.$tag$, $tag$https://llmclicks.ai/$tag$, $tag$AI Visibility Tracker & Audit | LLMClicks.ai$tag$, $tag$Measure your brand's AI search visibility across LLMs. Track citations, analyze competitors, and optimize for generative engines with LLMClicks.ai.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/ai-visibility-audit$tag$, $tag$Free 120-Point AI Visibility Audit | LLMClicks.ai$tag$, 'features') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Free 120-Point AI Visibility Audit | LLMClicks.ai$tag$, $tag$Run a free 120-point AI Visibility Audit. Find why competitors get cited in ChatGPT & Perplexity and get a prioritized fix list in minutes.$tag$, $tag$https://llmclicks.ai/ai-visibility-audit/$tag$, $tag$Free 120-Point AI Visibility Audit | LLMClicks.ai$tag$, $tag$Run a free 120-point AI Visibility Audit. Find why competitors get cited in ChatGPT & Perplexity and get a prioritized fix list in minutes.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/ai-visibility-audit$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/ai-visibility-tracker$tag$, $tag$AI Visibility Tracker: Monitor LLM Mentions & Citations$tag$, 'features') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$AI Visibility Tracker: Monitor LLM Mentions & Citations$tag$, $tag$Track how often ChatGPT, Perplexity, Google AI, and Copilot mention your brand. Daily Share of Voice updates, competitor benchmarks, and citation alerts.$tag$, $tag$https://llmclicks.ai/ai-visibility-tracker/$tag$, $tag$AI Visibility Tracker: Monitor LLM Mentions & Citations$tag$, $tag$Track how often ChatGPT, Perplexity, Google AI, and Copilot mention your brand. Daily Share of Voice updates, competitor benchmarks, and citation alerts.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/ai-visibility-tracker$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/on-page-optimiser$tag$, $tag$On-Page AI Audit Tool | LLMClicks.ai$tag$, 'features') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$On-Page AI Audit Tool | LLMClicks.ai$tag$, $tag$Audit pages for AI retrieval readiness. Fix semantic structure, heading hierarchy, and schema gaps so LLMs read and cite your content accurately.$tag$, $tag$https://llmclicks.ai/on-page-optimiser/$tag$, $tag$On-Page AI Audit Tool | LLMClicks.ai$tag$, $tag$Audit pages for AI retrieval readiness. Fix semantic structure, heading hierarchy, and schema gaps so LLMs read and cite your content accurately.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/on-page-optimiser$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/query-fan-out-coverage$tag$, $tag$Analyze Query Fan-Out Coverage for AI Search$tag$, 'features') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Analyze Query Fan-Out Coverage for AI Search$tag$, $tag$Expand any seed query into 10-20 semantic variations and measure your brand's citation coverage gaps across ChatGPT, Perplexity, and Google AI.$tag$, $tag$https://llmclicks.ai/query-fan-out-coverage/$tag$, $tag$Analyze Query Fan-Out Coverage for AI Search$tag$, $tag$Expand any seed query into 10-20 semantic variations and measure your brand's citation coverage gaps across ChatGPT, Perplexity, and Google AI.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/query-fan-out-coverage$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/content-comparison$tag$, $tag$Content Comparison Tool | Compare Content for AI Visibility$tag$, 'features') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Content Comparison Tool | Compare Content for AI Visibility$tag$, $tag$Compare your content against competitors and AI-generated answers. Identify content gaps, topic coverage differences, and optimization opportunities to improve AI visibility.$tag$, $tag$https://llmclicks.ai/content-comparison/$tag$, $tag$Content Comparison Tool | Compare Content for AI Visibility$tag$, $tag$Compare your content against competitors and AI-generated answers. Identify content gaps, topic coverage differences, and optimization opportunities to improve AI visibility.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/content-comparison$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/content-embedding-analyzer$tag$, $tag$Content Embedding Analyzer: Map Your Semantic Entities$tag$, 'features') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Content Embedding Analyzer: Map Your Semantic Entities$tag$, $tag$Check semantic alignment between your content and AI queries. Improve embedding relevance to increase citation probability in RAG-based LLM answers.$tag$, $tag$https://llmclicks.ai/content-embedding-analyzer/$tag$, $tag$Content Embedding Analyzer: Map Your Semantic Entities$tag$, $tag$Check semantic alignment between your content and AI queries. Improve embedding relevance to increase citation probability in RAG-based LLM answers.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/content-embedding-analyzer$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/ai-query-mapper$tag$, $tag$AI Query Mapper: Track Generative Search Intent$tag$, 'features') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$AI Query Mapper: Track Generative Search Intent$tag$, $tag$Connect Google Search Console queries to AI intent signals. Map what users search to what ChatGPT and Perplexity actually answer about your brand.$tag$, $tag$https://llmclicks.ai/ai-query-mapper/$tag$, $tag$AI Query Mapper: Track Generative Search Intent$tag$, $tag$Connect Google Search Console queries to AI intent signals. Map what users search to what ChatGPT and Perplexity actually answer about your brand.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/ai-query-mapper$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/industry-benchmarks$tag$, $tag$SaaS Industry Benchmarks for AI Search Visibility$tag$, 'resources') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$SaaS Industry Benchmarks for AI Search Visibility$tag$, $tag$See how your brand's AI citation rate compares across industries. LLMClicks.ai tracks Share of Voice benchmarks for SaaS, insurance, legal, and more.$tag$, $tag$https://llmclicks.ai/industry-benchmarks/$tag$, $tag$SaaS Industry Benchmarks for AI Search Visibility$tag$, $tag$See how your brand's AI citation rate compares across industries. LLMClicks.ai tracks Share of Voice benchmarks for SaaS, insurance, legal, and more.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/industry-benchmarks$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/llm-traffic-tracker$tag$, $tag$LLM Traffic Tracker: Measure AI Generated Search Clicks$tag$, 'features') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$LLM Traffic Tracker: Measure AI Generated Search Clicks$tag$, $tag$See which AI bots crawl your site and how often. Track GPTBot, ClaudeBot, PerplexityBot, and Googlebot per page. Free LLM traffic analytics tool.$tag$, $tag$https://llmclicks.ai/llm-traffic-tracker/$tag$, $tag$LLM Traffic Tracker: Measure AI Generated Search Clicks$tag$, $tag$See which AI bots crawl your site and how often. Track GPTBot, ClaudeBot, PerplexityBot, and Googlebot per page. Free LLM traffic analytics tool.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/llm-traffic-tracker$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/pricing$tag$, $tag$LLMClicks.ai Pricing | AI Visibility Plans$tag$, 'features') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$LLMClicks.ai Pricing | AI Visibility Plans$tag$, $tag$Choose the AI visibility plan that fits your team. From free tools to enterprise GEO tracking. 14-day free trial. No credit card required.$tag$, $tag$https://llmclicks.ai/pricing/$tag$, $tag$LLMClicks.ai Pricing | AI Visibility Plans$tag$, $tag$Choose the AI visibility plan that fits your team. From free tools to enterprise GEO tracking. 14-day free trial. No credit card required.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/pricing$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/ai-readiness-analyzer$tag$, $tag$Free AI Readiness Checker & Analyzer for B2B SaaS$tag$, 'free_tools') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Free AI Readiness Checker & Analyzer for B2B SaaS$tag$, $tag$Run a free 9-point AI readiness check in seconds. See if GPTBot, ClaudeBot, and PerplexityBot can crawl, parse, and cite your website. No login needed.$tag$, $tag$https://llmclicks.ai/ai-readiness-analyzer/$tag$, $tag$Free AI Readiness Checker & Analyzer for B2B SaaS$tag$, $tag$Run a free 9-point AI readiness check in seconds. See if GPTBot, ClaudeBot, and PerplexityBot can crawl, parse, and cite your website. No login needed.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/ai-readiness-analyzer$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/ai-domain-profiler$tag$, $tag$AI Domain Profiler: Analyze Your Generative Authority$tag$, 'free_tools') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$AI Domain Profiler: Analyze Your Generative Authority$tag$, $tag$Discover how ChatGPT and Gemini perceive your brand. Get your AI Visibility Score, entity graph, and tailored optimization checklist. No login required.$tag$, $tag$https://llmclicks.ai/ai-domain-profiler/$tag$, $tag$AI Domain Profiler: Analyze Your Generative Authority$tag$, $tag$Discover how ChatGPT and Gemini perceive your brand. Get your AI Visibility Score, entity graph, and tailored optimization checklist. No login required.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/ai-domain-profiler$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/ai-visibility-checker$tag$, $tag$Free AI Visibility Checker: Test Your Brand Mentions$tag$, 'free_tools') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Free AI Visibility Checker: Test Your Brand Mentions$tag$, $tag$Check if your brand appears in ChatGPT, Perplexity, and Google AI answers. Free AI visibility checker, no login needed. Results in under 60 seconds.$tag$, $tag$https://llmclicks.ai/ai-visibility-checker/$tag$, $tag$Free AI Visibility Checker: Test Your Brand Mentions$tag$, $tag$Check if your brand appears in ChatGPT, Perplexity, and Google AI answers. Free AI visibility checker, no login needed. Results in under 60 seconds.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/ai-visibility-checker$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/optimization-wizard$tag$, $tag$GEO Optimization Wizard: Step-by-Step AI Search Setup$tag$, 'features') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$GEO Optimization Wizard: Step-by-Step AI Search Setup$tag$, $tag$Get a step-by-step AI optimization plan personalized to your domain. Fix entity gaps, schema issues, and content alignment to increase LLM citation rates.$tag$, $tag$https://llmclicks.ai/optimization-wizard/$tag$, $tag$GEO Optimization Wizard: Step-by-Step AI Search Setup$tag$, $tag$Get a step-by-step AI optimization plan personalized to your domain. Fix entity gaps, schema issues, and content alignment to increase LLM citation rates.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/optimization-wizard$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/ai-listicle-marketplace$tag$, $tag$AI Listicle Marketplace: Secure Third-Party Citations$tag$, 'features') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$AI Listicle Marketplace: Secure Third-Party Citations$tag$, $tag$Get your SaaS product cited in AI-generated listicles on ChatGPT, Perplexity, and Google AI. LLMClicks.ai places your brand where B2B buyers research.$tag$, $tag$https://llmclicks.ai/ai-listicle-marketplace/$tag$, $tag$AI Listicle Marketplace: Secure Third-Party Citations$tag$, $tag$Get your SaaS product cited in AI-generated listicles on ChatGPT, Perplexity, and Google AI. LLMClicks.ai places your brand where B2B buyers research.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/ai-listicle-marketplace$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/affiliate-program$tag$, $tag$Join the LLMClicks.ai Partner & Affiliate Program$tag$, 'resources') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Join the LLMClicks.ai Partner & Affiliate Program$tag$, $tag$Earn up to 30% compounding recurring commission promoting the #1 AI visibility platform. Built for SEO agencies, consultants, and content creators.$tag$, $tag$https://llmclicks.ai/affiliate-program/$tag$, $tag$Join the LLMClicks.ai Partner & Affiliate Program$tag$, $tag$Earn up to 30% compounding recurring commission promoting the #1 AI visibility platform. Built for SEO agencies, consultants, and content creators.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/affiliate-program$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/about-us$tag$, $tag$About LLMClicks.ai | Our Mission to Improve AI Visibility$tag$, 'company') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$About LLMClicks.ai | Our Mission to Improve AI Visibility$tag$, $tag$We help brands appear in AI search results. LLMClicks.ai is trusted by agencies and marketers to track, analyze, and boost visibility across ChatGPT and beyond.$tag$, $tag$https://llmclicks.ai/about-us/$tag$, $tag$About LLMClicks.ai | Our Mission to Improve AI Visibility$tag$, $tag$We help brands appear in AI search results. LLMClicks.ai is trusted by agencies and marketers to track, analyze, and boost visibility across ChatGPT and beyond.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/about-us$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/contact$tag$, $tag$Contact LLMClicks.ai | Talk to Our AI Visibility Team$tag$, 'company') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Contact LLMClicks.ai | Talk to Our AI Visibility Team$tag$, $tag$Get in touch with the LLMClicks.ai team. Ask about pricing, demos, partnerships, or how to improve your brand visibility across AI search engines.$tag$, $tag$https://llmclicks.ai/contact/$tag$, $tag$Contact LLMClicks.ai | Talk to Our AI Visibility Team$tag$, $tag$Get in touch with the LLMClicks.ai team. Ask about pricing, demos, partnerships, or how to improve your brand visibility across AI search engines.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/contact$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/thank-you$tag$, $tag$Thank You | LLMClicks.ai$tag$, 'company') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Thank You | LLMClicks.ai$tag$, $tag$Thanks for reaching out to LLMClicks.ai. Our team will get back to you shortly.$tag$, $tag$https://llmclicks.ai/thank-you/$tag$, $tag$Thank You | LLMClicks.ai$tag$, $tag$Thanks for reaching out to LLMClicks.ai. Our team will get back to you shortly.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/thank-you$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/privacy-policy$tag$, $tag$Privacy Policy | LLMClicks.ai$tag$, 'legal') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Privacy Policy | LLMClicks.ai$tag$, $tag$Read the LLMClicks.ai privacy policy to learn how we collect, use, and protect your data.$tag$, $tag$https://llmclicks.ai/privacy-policy/$tag$, $tag$Privacy Policy | LLMClicks.ai$tag$, $tag$Read the LLMClicks.ai privacy policy to learn how we collect, use, and protect your data.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/privacy-policy$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/terms$tag$, $tag$Terms of Service | LLMClicks.ai$tag$, 'legal') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Terms of Service | LLMClicks.ai$tag$, $tag$Read the LLMClicks.ai terms of service governing use of our AI visibility platform.$tag$, $tag$https://llmclicks.ai/terms/$tag$, $tag$Terms of Service | LLMClicks.ai$tag$, $tag$Read the LLMClicks.ai terms of service governing use of our AI visibility platform.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/terms$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/ai-visibility-tool-comparison$tag$, $tag$AI Visibility Tool Comparison | LLMClicks.ai vs Alternatives$tag$, 'features') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$AI Visibility Tool Comparison | LLMClicks.ai vs Alternatives$tag$, $tag$Compare LLMClicks.ai with other AI visibility tools. See features, pricing, and accuracy across ChatGPT, Gemini, Claude, and Perplexity tracking.$tag$, $tag$https://llmclicks.ai/ai-visibility-tool-comparison/$tag$, $tag$AI Visibility Tool Comparison | LLMClicks.ai vs Alternatives$tag$, $tag$Compare LLMClicks.ai with other AI visibility tools. See features, pricing, and accuracy across ChatGPT, Gemini, Claude, and Perplexity tracking.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/ai-visibility-tool-comparison$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog$tag$, $tag$LLMClicks Blog | AI Visibility, GEO & LLM SEO Insights$tag$, 'resources') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$LLMClicks Blog | AI Visibility, GEO & LLM SEO Insights$tag$, $tag$Insights, guides, and case studies on AI search, LLM SEO, and how to grow brand visibility across ChatGPT, Gemini, Claude, and Perplexity.$tag$, $tag$https://llmclicks.ai/blog/$tag$, $tag$LLMClicks Blog | AI Visibility, GEO & LLM SEO Insights$tag$, $tag$Insights, guides, and case studies on AI search, LLM SEO, and how to grow brand visibility across ChatGPT, Gemini, Claude, and Perplexity.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/docs$tag$, $tag$Documentation | LLMClicks.ai$tag$, 'resources') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Documentation | LLMClicks.ai$tag$, $tag$Documentation for LLMClicks.ai â set up projects, run audits, track AI visibility, and integrate with your workflow.$tag$, $tag$https://llmclicks.ai/docs/$tag$, $tag$Documentation | LLMClicks.ai$tag$, $tag$Documentation for LLMClicks.ai â set up projects, run audits, track AI visibility, and integrate with your workflow.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/docs$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/knowledge-hub$tag$, $tag$Knowledge Hub | LLMClicks.ai$tag$, 'resources') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Knowledge Hub | LLMClicks.ai$tag$, $tag$The LLMClicks.ai Knowledge Hub: deep guides on AI visibility, generative search, and optimizing for LLM-powered discovery.$tag$, $tag$https://llmclicks.ai/knowledge-hub/$tag$, $tag$Knowledge Hub | LLMClicks.ai$tag$, $tag$The LLMClicks.ai Knowledge Hub: deep guides on AI visibility, generative search, and optimizing for LLM-powered discovery.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/knowledge-hub$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/web-stories$tag$, $tag$Web Stories | Generative SEO & AI Visibility | LLMClicks.ai$tag$, 'resources') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Web Stories | Generative SEO & AI Visibility | LLMClicks.ai$tag$, $tag$Bite-sized strategic teardowns. Learn how to optimize your SaaS for ChatGPT, Gemini, and Perplexity in 15 seconds or less.$tag$, $tag$https://llmclicks.ai/web-stories/$tag$, $tag$Web Stories | Generative SEO & AI Visibility | LLMClicks.ai$tag$, $tag$Bite-sized strategic teardowns. Learn how to optimize your SaaS for ChatGPT, Gemini, and Perplexity in 15 seconds or less.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/web-stories$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/on-page-audit-120-point-guide$tag$, $tag$120-Point On-Page Audit Guide for AI Search Readiness$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$120-Point On-Page Audit Guide for AI Search Readiness$tag$, $tag$The complete 120-point on-page audit guide for AI search. Fix schema, semantic structure, and entity gaps to rank in ChatGPT and Perplexity.$tag$, $tag$https://llmclicks.ai/blog/on-page-audit-120-point-guide/$tag$, $tag$120-Point On-Page Audit Guide for AI Search Readiness$tag$, $tag$The complete 120-point on-page audit guide for AI search. Fix schema, semantic structure, and entity gaps to rank in ChatGPT and Perplexity.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/on-page-audit-120-point-guide$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/top-ai-visibility-tracker-tools$tag$, $tag$11 Best AI Visibility Tracker Tools for B2B SaaS | Tested$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$11 Best AI Visibility Tracker Tools for B2B SaaS | Tested$tag$, $tag$We tested 11 AI visibility tracking tools. See which tracks citations across ChatGPT, Perplexity, and Google AI best. Full reviews and comparison table.$tag$, $tag$https://llmclicks.ai/blog/top-ai-visibility-tracker-tools/$tag$, $tag$11 Best AI Visibility Tracker Tools for B2B SaaS | Tested$tag$, $tag$We tested 11 AI visibility tracking tools. See which tracks citations across ChatGPT, Perplexity, and Google AI best. Full reviews and comparison table.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/top-ai-visibility-tracker-tools$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/ai-visibility-guide-for-llms$tag$, $tag$The Ultimate AI Visibility Guide for LLM Search$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$The Ultimate AI Visibility Guide for LLM Search$tag$, $tag$Learn how to improve your brand's visibility in LLM-generated answers. The complete guide to GEO, entity optimization, and AI citation strategy for 2026.$tag$, $tag$https://llmclicks.ai/blog/ai-visibility-guide-for-llms/$tag$, $tag$The Ultimate AI Visibility Guide for LLM Search$tag$, $tag$Learn how to improve your brand's visibility in LLM-generated answers. The complete guide to GEO, entity optimization, and AI citation strategy for 2026.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/ai-visibility-guide-for-llms$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/llm-visibility-vs-traditional-seo$tag$, $tag$LLM Visibility vs. Traditional SEO: The Core Differences$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$LLM Visibility vs. Traditional SEO: The Core Differences$tag$, $tag$Traditional SEO ranks pages. LLM SEO gets your brand cited in AI answers. Learn the core differences and how to optimize for both in 2026.$tag$, $tag$https://llmclicks.ai/blog/llm-visibility-vs-traditional-seo/$tag$, $tag$LLM Visibility vs. Traditional SEO: The Core Differences$tag$, $tag$Traditional SEO ranks pages. LLM SEO gets your brand cited in AI answers. Learn the core differences and how to optimize for both in 2026.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/llm-visibility-vs-traditional-seo$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/ai-visibility-measurement-guide$tag$, $tag$How to Measure AI Visibility: A Complete Framework$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$How to Measure AI Visibility: A Complete Framework$tag$, $tag$The complete framework for measuring AI visibility. Track brand citations, Share of Voice, and GEO performance across ChatGPT and Perplexity.$tag$, $tag$https://llmclicks.ai/blog/ai-visibility-measurement-guide/$tag$, $tag$How to Measure AI Visibility: A Complete Framework$tag$, $tag$The complete framework for measuring AI visibility. Track brand citations, Share of Voice, and GEO performance across ChatGPT and Perplexity.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/ai-visibility-measurement-guide$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/perplexity-seo-reverse-engineering$tag$, $tag$Reverse Engineering Perplexity SEO: How to Get Cited$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Reverse Engineering Perplexity SEO: How to Get Cited$tag$, $tag$Reverse-engineered: how Perplexity AI selects sources and ranks answers. The exact tactics to get your content cited in Perplexity search results.$tag$, $tag$https://llmclicks.ai/blog/perplexity-seo-reverse-engineering/$tag$, $tag$Reverse Engineering Perplexity SEO: How to Get Cited$tag$, $tag$Reverse-engineered: how Perplexity AI selects sources and ranks answers. The exact tactics to get your content cited in Perplexity search results.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/perplexity-seo-reverse-engineering$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/generative-engine-optimization-geo-saas$tag$, $tag$Generative Engine Optimization (GEO) Playbook for SaaS$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Generative Engine Optimization (GEO) Playbook for SaaS$tag$, $tag$The complete GEO playbook for B2B SaaS. Optimize your brand for ChatGPT and Perplexity citations and stop losing buyers to AI-generated answers.$tag$, $tag$https://llmclicks.ai/blog/generative-engine-optimization-geo-saas/$tag$, $tag$Generative Engine Optimization (GEO) Playbook for SaaS$tag$, $tag$The complete GEO playbook for B2B SaaS. Optimize your brand for ChatGPT and Perplexity citations and stop losing buyers to AI-generated answers.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/generative-engine-optimization-geo-saas$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/ai-brand-reputation-management-hallucinations$tag$, $tag$Fix Hallucinations with AI Brand Reputation Management$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Fix Hallucinations with AI Brand Reputation Management$tag$, $tag$AI platforms get your brand wrong. Learn how to detect, correct, and prevent LLM hallucinations using GEO and entity optimization techniques.$tag$, $tag$https://llmclicks.ai/blog/ai-brand-reputation-management-hallucinations/$tag$, $tag$Fix Hallucinations with AI Brand Reputation Management$tag$, $tag$AI platforms get your brand wrong. Learn how to detect, correct, and prevent LLM hallucinations using GEO and entity optimization techniques.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/ai-brand-reputation-management-hallucinations$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/seo-trends-agency-ai-audits$tag$, $tag$SEO Trends: Why Marketing Agencies Must Offer AI Audits$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$SEO Trends: Why Marketing Agencies Must Offer AI Audits$tag$, $tag$Top SEO agencies are adding AI audits to every client engagement. See the 2026 trends driving the shift from keyword rankings to LLM citation tracking.$tag$, $tag$https://llmclicks.ai/blog/seo-trends-agency-ai-audits/$tag$, $tag$SEO Trends: Why Marketing Agencies Must Offer AI Audits$tag$, $tag$Top SEO agencies are adding AI audits to every client engagement. See the 2026 trends driving the shift from keyword rankings to LLM citation tracking.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/seo-trends-agency-ai-audits$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/best-ai-seo-tools$tag$, $tag$The 10 Best AI SEO Tools for 2026 (Ranked & Reviewed)$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$The 10 Best AI SEO Tools for 2026 (Ranked & Reviewed)$tag$, $tag$The 10 best AI SEO tools for 2026, ranked and reviewed. From LLM citation trackers to content analyzers, find which tools are worth your budget.$tag$, $tag$https://llmclicks.ai/blog/best-ai-seo-tools/$tag$, $tag$The 10 Best AI SEO Tools for 2026 (Ranked & Reviewed)$tag$, $tag$The 10 best AI SEO tools for 2026, ranked and reviewed. From LLM citation trackers to content analyzers, find which tools are worth your budget.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/best-ai-seo-tools$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/ai-visibility-framework-intent-mapping$tag$, $tag$AI Visibility Framework: Mastering Search Intent Mapping$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$AI Visibility Framework: Mastering Search Intent Mapping$tag$, $tag$Map user intent to AI answers. The AI visibility framework for aligning content with the queries ChatGPT and Perplexity surface to B2B buyers.$tag$, $tag$https://llmclicks.ai/blog/ai-visibility-framework-intent-mapping/$tag$, $tag$AI Visibility Framework: Mastering Search Intent Mapping$tag$, $tag$Map user intent to AI answers. The AI visibility framework for aligning content with the queries ChatGPT and Perplexity surface to B2B buyers.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/ai-visibility-framework-intent-mapping$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/ai-search-readiness-audit$tag$, $tag$How to Conduct an AI Search Readiness Audit for SaaS$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$How to Conduct an AI Search Readiness Audit for SaaS$tag$, $tag$Discover if your site is ready for AI search. This audit covers crawlability, JSON-LD schema, entity clarity, and content structure for LLM retrieval.$tag$, $tag$https://llmclicks.ai/blog/ai-search-readiness-audit/$tag$, $tag$How to Conduct an AI Search Readiness Audit for SaaS$tag$, $tag$Discover if your site is ready for AI search. This audit covers crawlability, JSON-LD schema, entity clarity, and content structure for LLM retrieval.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/ai-search-readiness-audit$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/monitor-competitor-mentions-ai-search$tag$, $tag$How to Monitor Competitor Mentions in AI Search Results$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$How to Monitor Competitor Mentions in AI Search Results$tag$, $tag$Track when competitors get cited by ChatGPT, Perplexity, and Google AI and you don't. Benchmark AI Share of Voice and close citation gaps fast.$tag$, $tag$https://llmclicks.ai/blog/monitor-competitor-mentions-ai-search/$tag$, $tag$How to Monitor Competitor Mentions in AI Search Results$tag$, $tag$Track when competitors get cited by ChatGPT, Perplexity, and Google AI and you don't. Benchmark AI Share of Voice and close citation gaps fast.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/monitor-competitor-mentions-ai-search$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/what-is-ai-search-visibility$tag$, $tag$What is AI Search Visibility? A Guide for SaaS Founders$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$What is AI Search Visibility? A Guide for SaaS Founders$tag$, $tag$AI search visibility measures how often your brand appears in LLM answers. Learn what it means, how it's measured, and how to improve it in 2026.$tag$, $tag$https://llmclicks.ai/blog/what-is-ai-search-visibility/$tag$, $tag$What is AI Search Visibility? A Guide for SaaS Founders$tag$, $tag$AI search visibility measures how often your brand appears in LLM answers. Learn what it means, how it's measured, and how to improve it in 2026.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/what-is-ai-search-visibility$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/semrush-ahrefs-ai-alternatives$tag$, $tag$Semrush & Ahrefs AI Alternatives for Visibility Tracking$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Semrush & Ahrefs AI Alternatives for Visibility Tracking$tag$, $tag$SEMrush and Ahrefs don't track LLM citations. Compare the best AI-native alternatives for monitoring brand visibility in ChatGPT and Perplexity.$tag$, $tag$https://llmclicks.ai/blog/semrush-ahrefs-ai-alternatives/$tag$, $tag$Semrush & Ahrefs AI Alternatives for Visibility Tracking$tag$, $tag$SEMrush and Ahrefs don't track LLM citations. Compare the best AI-native alternatives for monitoring brand visibility in ChatGPT and Perplexity.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/semrush-ahrefs-ai-alternatives$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/otterly-vs-peec-ai-alternative-llmclicks$tag$, $tag$Otterly vs Peec AI vs LLMClicks: Which is Best?$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Otterly vs Peec AI vs LLMClicks: Which is Best?$tag$, $tag$We compared Otterly, Peec AI, and LLMClicks.ai for tracking AI brand visibility. See which delivers the best features and value for SEO teams.$tag$, $tag$https://llmclicks.ai/blog/otterly-vs-peec-ai-alternative-llmclicks/$tag$, $tag$Otterly vs Peec AI vs LLMClicks: Which is Best?$tag$, $tag$We compared Otterly, Peec AI, and LLMClicks.ai for tracking AI brand visibility. See which delivers the best features and value for SEO teams.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/otterly-vs-peec-ai-alternative-llmclicks$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/how-llms-work$tag$, $tag$How LLMs Work: The Technical SEO Architecture Guide$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$How LLMs Work: The Technical SEO Architecture Guide$tag$, $tag$Learn how large language models retrieve and generate answers and what that means for your SEO strategy and AI citation optimization approach.$tag$, $tag$https://llmclicks.ai/blog/how-llms-work/$tag$, $tag$How LLMs Work: The Technical SEO Architecture Guide$tag$, $tag$Learn how large language models retrieve and generate answers and what that means for your SEO strategy and AI citation optimization approach.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/how-llms-work$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/future-of-ai-llm-visibility$tag$, $tag$The Future of AI Search: LLM Visibility Predictions$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$The Future of AI Search: LLM Visibility Predictions$tag$, $tag$AI search is replacing keyword rankings. See where LLM visibility is heading in 2026 and what separates cited brands from invisible ones.$tag$, $tag$https://llmclicks.ai/blog/future-of-ai-llm-visibility/$tag$, $tag$The Future of AI Search: LLM Visibility Predictions$tag$, $tag$AI search is replacing keyword rankings. See where LLM visibility is heading in 2026 and what separates cited brands from invisible ones.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/future-of-ai-llm-visibility$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/ai-visibility-tool-affiliate-program$tag$, $tag$Earn Revenue with our AI Visibility Tool Affiliate Program$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Earn Revenue with our AI Visibility Tool Affiliate Program$tag$, $tag$Promote LLMClicks.ai and earn 30% recurring commission on every referral. Built for SEO bloggers, agency owners, and AI marketing consultants.$tag$, $tag$https://llmclicks.ai/blog/ai-visibility-tool-affiliate-program/$tag$, $tag$Earn Revenue with our AI Visibility Tool Affiliate Program$tag$, $tag$Promote LLMClicks.ai and earn 30% recurring commission on every referral. Built for SEO bloggers, agency owners, and AI marketing consultants.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/ai-visibility-tool-affiliate-program$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/ai-search-visibility-audit$tag$, $tag$Build an AI Search Visibility Audit for Your Clients$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Build an AI Search Visibility Audit for Your Clients$tag$, $tag$The complete AI search visibility audit. Identify crawl gaps, missing schema, and entity issues that block your brand from LLM citations.$tag$, $tag$https://llmclicks.ai/blog/ai-search-visibility-audit/$tag$, $tag$Build an AI Search Visibility Audit for Your Clients$tag$, $tag$The complete AI search visibility audit. Identify crawl gaps, missing schema, and entity issues that block your brand from LLM citations.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/ai-search-visibility-audit$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/llmclicks-backlink-marketplace-comprehensive-user-guide$tag$, $tag$LLMClicks Backlink Marketplace: Complete User Guide$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$LLMClicks Backlink Marketplace: Complete User Guide$tag$, $tag$Your complete guide to the LLMClicks.ai Backlink Marketplace. Learn how to filter domains by AI relevance, track orders, and monetize your existing site inventory.$tag$, $tag$https://llmclicks.ai/blog/llmclicks-backlink-marketplace-comprehensive-user-guide/$tag$, $tag$LLMClicks Backlink Marketplace: Complete User Guide$tag$, $tag$Your complete guide to the LLMClicks.ai Backlink Marketplace. Learn how to filter domains by AI relevance, track orders, and monetize your existing site inventory.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/llmclicks-backlink-marketplace-comprehensive-user-guide$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/why-faqs-fail-llm-seo-nyc-personal-injury-case-study$tag$, $tag$Why FAQs Fail for LLM SEO: NYC Injury Law Case Study$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Why FAQs Fail for LLM SEO: NYC Injury Law Case Study$tag$, $tag$We analyzed 100+ NYC personal injury pages with FAQs. See why 76% fail LLM SEO, what ChatGPT rewards instead, and how intent-aligned FAQs boost visibility.$tag$, $tag$https://llmclicks.ai/blog/why-faqs-fail-llm-seo-nyc-personal-injury-case-study/$tag$, $tag$Why FAQs Fail for LLM SEO: NYC Injury Law Case Study$tag$, $tag$We analyzed 100+ NYC personal injury pages with FAQs. See why 76% fail LLM SEO, what ChatGPT rewards instead, and how intent-aligned FAQs boost visibility.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/why-faqs-fail-llm-seo-nyc-personal-injury-case-study$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/ai-visibility-benchmark-general-insurance-usa-2025$tag$, $tag$AI Visibility Benchmark: US Insurance Industry 2026$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$AI Visibility Benchmark: US Insurance Industry 2026$tag$, $tag$Discover which U.S. insurers lead in AI visibility across ChatGPT and Perplexity. The 2025 benchmark by LLMClicks.ai reveals leaders, gaps, and growth insights.$tag$, $tag$https://llmclicks.ai/blog/ai-visibility-benchmark-general-insurance-usa-2025/$tag$, $tag$AI Visibility Benchmark: US Insurance Industry 2026$tag$, $tag$Discover which U.S. insurers lead in AI visibility across ChatGPT and Perplexity. The 2025 benchmark by LLMClicks.ai reveals leaders, gaps, and growth insights.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/ai-visibility-benchmark-general-insurance-usa-2025$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/do-llms-care-about-backlinks-or-domain-age$tag$, $tag$Do LLMs Care About Backlinks or Domain Age?$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Do LLMs Care About Backlinks or Domain Age?$tag$, $tag$We tested India's top insurers across ChatGPT and Perplexity. See which brands lead in AI visibility and why traditional Google rankings now mean less.$tag$, $tag$https://llmclicks.ai/blog/do-llms-care-about-backlinks-or-domain-age/$tag$, $tag$Do LLMs Care About Backlinks or Domain Age?$tag$, $tag$We tested India's top insurers across ChatGPT and Perplexity. See which brands lead in AI visibility and why traditional Google rankings now mean less.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/do-llms-care-about-backlinks-or-domain-age$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/chatgpt-as-gtm-strategist-llmclicks-case-study$tag$, $tag$ChatGPT as a GTM Strategist: LLMClicks Case Study$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$ChatGPT as a GTM Strategist: LLMClicks Case Study$tag$, $tag$Learn how LLMClicks.ai used ChatGPT as its GTM strategist to plan, launch, and grow, reaching 637 users with ₹0 ad spend in this practical SaaS case study.$tag$, $tag$https://llmclicks.ai/blog/chatgpt-as-gtm-strategist-llmclicks-case-study/$tag$, $tag$ChatGPT as a GTM Strategist: LLMClicks Case Study$tag$, $tag$Learn how LLMClicks.ai used ChatGPT as its GTM strategist to plan, launch, and grow, reaching 637 users with ₹0 ad spend in this practical SaaS case study.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/chatgpt-as-gtm-strategist-llmclicks-case-study$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/blog/ai-visibility-benchmark-general-insurance-india-2025$tag$, $tag$AI Visibility Benchmark: India Insurance Industry 2026$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$AI Visibility Benchmark: India Insurance Industry 2026$tag$, $tag$We tested India's top insurers across ChatGPT and Perplexity. See which brands lead in AI visibility and why traditional Google rankings now mean less.$tag$, $tag$https://llmclicks.ai/blog/ai-visibility-benchmark-general-insurance-india-2025/$tag$, $tag$AI Visibility Benchmark: India Insurance Industry 2026$tag$, $tag$We tested India's top insurers across ChatGPT and Perplexity. See which brands lead in AI visibility and why traditional Google rankings now mean less.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/blog/ai-visibility-benchmark-general-insurance-india-2025$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/knowledge-hub/chatgpt-seo/blocking-gptbot-seo$tag$, $tag$Should You Block GPTBot? The SEO Consequences$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Should You Block GPTBot? The SEO Consequences$tag$, $tag$Blocking GPTBot prevents ChatGPT from crawling and citing your site. Learn the SEO and GEO impact and the correct robots.txt configuration to fix it.$tag$, $tag$https://llmclicks.ai/knowledge-hub/chatgpt-seo/blocking-gptbot-seo/$tag$, $tag$Should You Block GPTBot? The SEO Consequences$tag$, $tag$Blocking GPTBot prevents ChatGPT from crawling and citing your site. Learn the SEO and GEO impact and the correct robots.txt configuration to fix it.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/knowledge-hub/chatgpt-seo/blocking-gptbot-seo$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/knowledge-hub/ai-overviews/google-ai-overviews-optimization$tag$, $tag$Google AI Overviews vs Traditional SERPs: How to Optimize$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Google AI Overviews vs Traditional SERPs: How to Optimize$tag$, $tag$Optimize your pages for Google AI Overviews. Covers structured data, content formatting, entity clarity, and E-E-A-T signals for AI citation inclusion.$tag$, $tag$https://llmclicks.ai/knowledge-hub/ai-overviews/google-ai-overviews-optimization/$tag$, $tag$Google AI Overviews vs Traditional SERPs: How to Optimize$tag$, $tag$Optimize your pages for Google AI Overviews. Covers structured data, content formatting, entity clarity, and E-E-A-T signals for AI citation inclusion.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/knowledge-hub/ai-overviews/google-ai-overviews-optimization$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/knowledge-hub/agentic-search-aeo/agentic-engine-optimization-b2b-saas-seo$tag$, $tag$Agentic Engine Optimization (AEO) for B2B SaaS$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Agentic Engine Optimization (AEO) for B2B SaaS$tag$, $tag$AI agents evaluate your SaaS product without human direction. Learn how Agentic Engine Optimization structures your data for autonomous discovery.$tag$, $tag$https://llmclicks.ai/knowledge-hub/agentic-search-aeo/agentic-engine-optimization-b2b-saas-seo/$tag$, $tag$Agentic Engine Optimization (AEO) for B2B SaaS$tag$, $tag$AI agents evaluate your SaaS product without human direction. Learn how Agentic Engine Optimization structures your data for autonomous discovery.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/knowledge-hub/agentic-search-aeo/agentic-engine-optimization-b2b-saas-seo$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/web-stories/ai-visibility-tracker-tools$tag$, $tag$10 Top AI Visibility Tracker Tools$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$10 Top AI Visibility Tracker Tools$tag$, $tag$Quick visual guide to the top AI visibility trackers. See which tools monitor brand citations in ChatGPT, Perplexity, and Google AI.$tag$, $tag$https://llmclicks.ai/web-stories/ai-visibility-tracker-tools/$tag$, $tag$10 Top AI Visibility Tracker Tools$tag$, $tag$Quick visual guide to the top AI visibility trackers. See which tools monitor brand citations in ChatGPT, Perplexity, and Google AI.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/web-stories/ai-visibility-tracker-tools$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/web-stories/reverse-engineer-perplexity-seo$tag$, $tag$How to Reverse Engineer Perplexity SEO$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$How to Reverse Engineer Perplexity SEO$tag$, $tag$Visual step-by-step breakdown of how Perplexity AI selects and cites sources and how to get your brand included in its answers.$tag$, $tag$https://llmclicks.ai/web-stories/reverse-engineer-perplexity-seo/$tag$, $tag$How to Reverse Engineer Perplexity SEO$tag$, $tag$Visual step-by-step breakdown of how Perplexity AI selects and cites sources and how to get your brand included in its answers.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/web-stories/reverse-engineer-perplexity-seo$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/web-stories/fix-ai-brand-hallucinations$tag$, $tag$3 Steps to Fix AI Brand Hallucinations$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$3 Steps to Fix AI Brand Hallucinations$tag$, $tag$AI platforms get your brand wrong. This visual guide shows how to detect and correct LLM hallucinations about your business in 3 steps.$tag$, $tag$https://llmclicks.ai/web-stories/fix-ai-brand-hallucinations/$tag$, $tag$3 Steps to Fix AI Brand Hallucinations$tag$, $tag$AI platforms get your brand wrong. This visual guide shows how to detect and correct LLM hallucinations about your business in 3 steps.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/web-stories/fix-ai-brand-hallucinations$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/web-stories/chatgpt-stealing-clicks$tag$, $tag$Is ChatGPT Stealing Your Organic Clicks?$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Is ChatGPT Stealing Your Organic Clicks?$tag$, $tag$ChatGPT answers questions your pages used to rank for. See the data behind AI click cannibalization and how to reclaim visibility in LLM answers.$tag$, $tag$https://llmclicks.ai/web-stories/chatgpt-stealing-clicks/$tag$, $tag$Is ChatGPT Stealing Your Organic Clicks?$tag$, $tag$ChatGPT answers questions your pages used to rank for. See the data behind AI click cannibalization and how to reclaim visibility in LLM answers.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/web-stories/chatgpt-stealing-clicks$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/web-stories/ai-citations-vs-backlinks$tag$, $tag$AI Citations vs Traditional Backlinks$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$AI Citations vs Traditional Backlinks$tag$, $tag$Backlinks built traditional SEO. AI citations build LLM visibility. See the data on which signal matters more for brand discovery in 2026.$tag$, $tag$https://llmclicks.ai/web-stories/ai-citations-vs-backlinks/$tag$, $tag$AI Citations vs Traditional Backlinks$tag$, $tag$Backlinks built traditional SEO. AI citations build LLM visibility. See the data on which signal matters more for brand discovery in 2026.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/web-stories/ai-citations-vs-backlinks$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/web-stories/rank-google-ai-overviews$tag$, $tag$How to Rank in Google AI Overviews$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$How to Rank in Google AI Overviews$tag$, $tag$A visual guide to getting featured in Google AI Overviews. Covers content structure, schema, E-E-A-T, and the page signals Google's AI prioritizes.$tag$, $tag$https://llmclicks.ai/web-stories/rank-google-ai-overviews/$tag$, $tag$How to Rank in Google AI Overviews$tag$, $tag$A visual guide to getting featured in Google AI Overviews. Covers content structure, schema, E-E-A-T, and the page signals Google's AI prioritizes.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/web-stories/rank-google-ai-overviews$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

INSERT INTO public.pages (path, title, section) VALUES ($tag$/author/shripad-deshmukh$tag$, $tag$Shripad Deshmukh — Founder, LLMClicks.ai$tag$, 'none') ON CONFLICT (path) DO UPDATE SET title=EXCLUDED.title, section=EXCLUDED.section;
INSERT INTO public.page_seo (page_id, meta_title, meta_description, canonical_url, og_title, og_description, robots) SELECT id, $tag$Shripad Deshmukh — Founder, LLMClicks.ai$tag$, $tag$Shripad Deshmukh is the founder of LLMClicks.ai, an AI visibility platform helping brands get cited in ChatGPT, Perplexity, and Google AI Overviews.$tag$, $tag$https://llmclicks.ai/author/shripad-deshmukh/$tag$, $tag$Shripad Deshmukh — Founder, LLMClicks.ai$tag$, $tag$Shripad Deshmukh is the founder of LLMClicks.ai, an AI visibility platform helping brands get cited in ChatGPT, Perplexity, and Google AI Overviews.$tag$, 'index,follow' FROM public.pages WHERE path=$tag$/author/shripad-deshmukh$tag$ ON CONFLICT (page_id) DO UPDATE SET meta_title=EXCLUDED.meta_title, meta_description=EXCLUDED.meta_description, canonical_url=EXCLUDED.canonical_url, og_title=EXCLUDED.og_title, og_description=EXCLUDED.og_description, robots=EXCLUDED.robots;

COMMIT;
